const links = [
  {
    label: 'gitHub',
    icon: "<i class='bi bi-github'></i>",
    url: 'https://github.com/IsTaro',
  },
  {
    label: 'twitter',
    icon: "<i class='bi bi-twitter'></i>",
    url: 'https://twitter.com/shotaro191',
  },
  {
    label: 'email',
    icon: "<i class='bi bi-envelope'></i>",
    url: 'mailto:learn42317@gmail.com',
  },
]


const data = [
  {
    id: 1,
    category: 'react',
    title: 'random quote machine',
    img: './images/random-quote-machine.png',
    url: 'https://istaro.github.io/react-app-random-quote-machine/',
    difficulty: 2,
    desc: '',
  },
  {
    id: 2,
    category: 'react',
    title: 'drum machine',
    img: './images/drum-machine.png',
    url: 'https://unrivaled-treacle-461848.netlify.app/',
    difficulty: 3,
  },
  {
    id: 3,
    category: 'react',
    title: 'calculator',
    img: './images/calculator.png',
    url: 'https://tranquil-beignet-155758.netlify.app/',
    difficulty: 3,
  },
  {
    id: 4,
    category: 'react',
    title: '25clock',
    img: './images/25clock.png',
    url: 'https://sprightly-taiyaki-f87361.netlify.app/',
    difficulty: 3,
  },
  {
    id: 5,
    category: 'react',
    title: 'markdown previewwer',
    img: './images/markdown-previewwer.png',
    url: 'https://vocal-biscotti-540ef9.netlify.app/',
    difficulty: 2,
  },
  {
    id: 6,
    category: 'vanilla-js',
    title: 'interactive rating component',
    img: './images/interactive-rating-component.png',
    url: 'https://celebrated-pika-e69aaf.netlify.app/',
    difficulty: 1,
  },
  {
    id: 7,
    category: 'vanilla-js',
    title: 'launch countdown timer',
    img: './images/launch-countdown-timer.png',
    url: 'https://moonlit-youtiao-0892f7.netlify.app/',
    difficulty: 3,
  },
  {
    id: 8,
    category: 'vanilla-js',
    title: 'ecommerce product page',
    img: './images/ecommerce-product-page.png',
    url: 'https://subtle-gumption-59ff95.netlify.app/',
    difficulty: 3,
  },
  {
    id: 9,
    category: 'html/css',
    title: 'ip address tracker',
    img: './images/ip-address-tracker.png',
    url: 'https://chic-caramel-a9b91e.netlify.app/',
    difficulty: 3,
  },
  {
    id: 10,
    category: 'vanilla-js',
    title: 'show the local weather',
    img: './images/show-the-local-weather.png',
    url: 'https://thunderous-travesseiro-456d5b.netlify.app/',
    difficulty: 2,
  },
  {
    id: 11,
    category: 'clone-site',
    title: 'clone ableton',
    img: './images/clone-ableton.png',
    url: 'https://genuine-gnome-9a8333.netlify.app/',
    difficulty: 4,
  },
  {
    id: 12,
    category: 'clone-site',
    title: 'clone backstage talks',
    img: './images/clone-backstage-talks.png',
    url: 'https://glittering-bonbon-800429.netlify.app/',
    difficulty: 3,
  },
  // {
  //   id: 13,
  //   category: 'react',
  //   title: 'to do list',
  //   img: './images/to-do-list.png',
  //   url: 'https://istaro.github.io/to-do-list/',
  //   difficulty: 3,
  // },
  {
    id: 13,
    category: 'react',
    title: 'wikipedia viewer',
    img: './images/wikipedia-viewer.png',
    url: 'https://istaro.github.io/wikipedia-viewer/',
    difficulty: 3,
  },
]

export { data, links }
